### ISSUE TITLE
NullPointerException in BeaconService.matchingRegions()

### ISSUE THREAD

**Issue by mykolaj** [AltBeacon/android-beacon-library#212]
Hello!
I've got an issue which doesn't seem to depend on Android version or AltBeaconLib version. Anyways, it is currently confirmed to occur on some of Kyocera and Samsung devices running Android 4.4 and Android 5.0 and AltBeaconLib 2.1.4. Here's a stack trace:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.altbeacon.beacon.Region.matchesBeacon(org.altbeacon.beacon.Beacon)' on a null object reference
at org.altbeacon.beacon.service.BeaconService.matchingRegions(BeaconService.java:462)
at org.altbeacon.beacon.service.BeaconService.processBeaconFromScan(BeaconService.java:399)
at org.altbeacon.beacon.service.BeaconService.access$400(BeaconService.java:66)
at org.altbeacon.beacon.service.BeaconService$ScanProcessor.doInBackground(BeaconService.java:439)
at org.altbeacon.beacon.service.BeaconService$ScanProcessor.doInBackground(BeaconService.java:422)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
```

So far it happens from time to time without any visible regularity, so i can't reproduce it on purpose, but it happens quite often. Here's some code details:
`// Start ranging`
`mRegion = new Region(UUID.randomUUID().toString(), null, null, null);`
`mBeaconManager.startRangingBeaconsInRegion(mRegion);`
 (UUID is changed when a program is restarted)

After some time (could be minutes, could be hours) a program crashes with the above exception.
Also it's worth to say that scan is searching for iBeacons, and seams to happen when there are a lot of Bluetooth devices nearby .

This exception happens inside next loop: 

``` java
           Iterator<Region> regionIterator = regions.iterator();
            while (regionIterator.hasNext()) {
                Region region = regionIterator.next();
                if (region.matchesBeacon(beacon)) {
                    matched.add(region);
                } else {
                    LogManager.d(TAG, "This region (%s) does not match beacon: %s", region, beacon);
                }
            }
```

Of course a quickfix would be to just check if a Region is null and continue the loop if it is. Or is there any purpose for `null` key in `rangedRegionState` and `monitoredRegionState` maps?
Thank you!

**Comment by davidgyoung** [comment]
It looks like this is most likely a threading issue and is not specific to a phone model.  Do you have reason to believe it is only an issue with "some Kyocera and Samsung devices" and not other models?

**Comment by mykolaj** [comment]
I'm also thinking it is most likely a threading issue. I've just mentioned those phone models because those the phones i'm currently working with. This issue happened on other models too (one LG for sure). So, no. I think there's no reason to believe that this issue happens only on mentioned phones.
I will continue to look to find a solution now when i know that `null` is not for purpose.
By the way, the library is great!

**Comment by davidgyoung** [comment]
Proposed fix here: https://github.com/AltBeacon/android-beacon-library/pull/215

**Comment by mykolaj** [comment]
Its been almost a year. I think its time to close this issue.

**Comment by davidgyoung** [comment]
Indded!  The proposed fix has been merged.

**Comment by tnortman** [comment]
I believe this bug is back.

Looks like the method `matchingRegions`, which in previous releases resided in `beacon/service/BeaconService.java` got moved to `beacon/service/ScanHelper.java`
and the null check is no longer there.

I updated my gradle dependency in my app from 
`    api 'org.altbeacon:android-beacon-library:2.9.1'`
to
`    api 'org.altbeacon:android-beacon-library:2.15.2'`
and now every time I launch my app (when beacons are in range), it crashes with the same stack trace as above. I am running Android 8.0 but I don't believe that matters

**Comment by davidgyoung** [comment]
Thanks for the report.  I'll look to add an equivalent check in ScanHelper.

**Comment by davidgyoung** [comment]
Fixed again in #770

**Comment by EnesKy** [comment]
I've got this error at API 26 when i create a Region in onCreate() and using it like global variable.
It might have happens because Region value created before onBeaconServiceConnect() call.

By the way i'm using the latest version. (2.16.2-beta1@aar)

![image](https://user-images.githubusercontent.com/25669076/56423470-dfce8600-62b4-11e9-86e8-82c1aff6a182.png)

**Comment by davidgyoung** [comment]
Argh!  It looks like my fix for this in #770 was never merged.  I accidentally closed the PR without merging it

**Comment by davidgyoung** [comment]
Ok, #770 merged to master now.  closing this issue for the third time!
